import { StyleSheet, StatusBar } from 'react-native';

export const MyStyles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
    },
    cbox: {
        flex: 1,
        margin: 2,
        width: '100%',
        height: '50%',
        flexDirection:'column',
    },
    mbox: {
        margin: 5,
        width: '100%',
        alignItems:'center',
        flexDirection: 'column',
    },
    TabContainer: {
        flex: 1,
        alignItems: 'center',
        paddingTop: 40,
    },
    header: {
        width: '100%',
        height: 160,
        backgroundColor: '#ffe6e6',
        padding: 35,
        paddingTop: StatusBar.currentHeight || 40,
        position: 'absolute', 
        top: 0, left: 0, right: 0,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: "#000",
        shadowOffset: { width: 10, height: 40 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    title: { 
        fontSize: 25, 
        fontWeight: 'bold',
        textAlign:'Left', 
        color: '#ac2e39', 
        marginBottom: 5, 
    },
    subtitle: { 
        fontSize: 18, 
        color: '#ac2e39', 
        marginBottom: 20,
        alignContent:'left', 
    },
    leftTextAlign: {
        alignSelf: 'flex-start',
        textAlign: 'left',
        marginLeft: 30,
        marginRight: 15,
    },
    centeredText: {
        textAlign: 'center',
        margin: 10,
        marginLeft: 15,
        marginRight: 15,
    },
    logo: { 
        width: 250, 
        height: 200, 
        marginBottom: 50, 
    },
    logo2: { 
        width: 50, 
        height: 50, 
        marginBottom: 10, 
        marginRight: 10,
        justifyContent: 'left'
    },
    backButton: { 
        width: 30, 
        height: 30, 
        marginBottom: 10, 
        marginRight: 10,
        justifyContent: 'left'
    },
    Gbutton: {
        paddingVertical: 12,
        paddingHorizontal: 30,
        width: 250,
        backgroundColor: 'white',
        borderRadius: 30,
        margin: 10,
        alignItems: 'center',
        justifyContent: 'center', 
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    buttonText: { 
        fontSize: 20, 
        fontWeight: 'bold', 
        color: 'white',
        textAlign: 'center',
    },
    Sbutton: {
        paddingVertical: 12,
        paddingHorizontal: 30,
        width: 300,
        backgroundColor: '#8B0000',
        borderRadius: 30,
        margin: 10,
        alignItems: 'center',
        justifyContent: 'center', 
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    input: {
        width: "85%",
        height: 45,
        borderWidth: 1,
        borderColor: '#8B0000',
        paddingLeft: 10,
        marginBottom: 10,
        backgroundColor: 'white',
        color: '#ac2e39',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sendButton: {
        backgroundColor: '#8B0000',
        width: '23%',
        height: 45,
        borderRadius: 30,
        marginLeft: 5,
        marginBottom: 10,
        justifyContent: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    sendButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize:12,
        textAlign:'center',
    },
    tabBar: {
        backgroundColor: '#ffe6e6',
        height: 70,
        borderWidth:2,
        borderTopLeftRadius: 40,
        borderTopRightRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 15,
        shadowColor: "#000",
        shadowOffset: { width: 10, height: 40 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    placeholder: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    greeting: {
        fontSize: 20,
        color: '#ac2e39',
        marginTop:20,
    },
    userName: {
        fontSize:30,
        fontWeight: 'bold',
        color: '#ac2e39',
    },
    profileImage: {
        width: 75,
        height: 75,
        borderWidth: 2,
        borderColor:'#8B0000',
        borderRadius: 50,
        marginTop:20,
        marginRight: 5
    },
    sosButton: {
        width: 150,
        height: 150,
        borderRadius: 75,
        backgroundColor: '#8B0000',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 40,
        marginBottom: 60,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    locationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffe6e6',
        padding: 10,
        width: '90%',
        borderRadius: 15,
        marginTop: 20, 
        justifyContent: 'center',
        alignSelf: 'center', 
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 2,
    },
    locationTextContainer: {
        flex: 1, 
        justifyContent: 'center',
    },
    locationIcon: {
        width: 55,
        height: 55,
        margin: 10,
        borderWidth: 2,
        borderRadius: 30,
        borderColor:'#8B0000',
    },
    cmButton: {
        width: '40%',
        height: 25,
        borderRadius: 30,
        marginTop:10,
        marginRight: 5,
        marginBottom: 5,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#8B0000',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    cmButton2 :{
        width: '40%',
        height: 25,
        borderRadius: 30,
        marginTop:10,
        marginRight: 5,
        marginBottom: 5,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#8B0000',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    contactsContainer: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        paddingTop: 20,
        backgroundColor: '#fff',
    },
    contactCard: {
        width: '85%',
        backgroundColor: '#ffe6e6',
        borderRadius: 15,
        padding: 10,
        marginBottom: 10,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    contactImage: {
        width: 55,
        height: 55,
        borderRadius: 30,
        borderWidth: 2,
        borderColor: '#8B0000',
        marginRight: 10,
    },
    contactInfo: {
        flex: 1,
    },
    contactName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#8B0000',
        marginBottom: 5,
    },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#8B0000',
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 20,
        marginTop: 5,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    addButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#8B0000',
        marginLeft: 10,
    },
    userPFP: {
        width: 150,
        height: 150,
        margin: 10,
        marginBottom: 30,
        borderWidth: 2,
        borderRadius: 550,
        borderColor:'#8B0000',
    },
    profileInfo: {
        fontSize: 16, 
        color: '#ac2e39', 
        marginTop: 10,
        marginBottom: 15,
        alignSelf: 'flex-start',
        marginLeft: 35,
        width: '80%',
        borderBottomWidth: 2, 
        borderBottomColor: '#ac2e39',
        paddingBottom: 5,
    },
    edit: {
        width: 25,
        height: 25,
        marginLeft: 35,
        marginBottom: 15,
        borderColor:'#8B0000',
    },
    back: {
        width: 25,
        height: 25,
        marginRight: 15,
        marginBottom: 15,
        borderColor:'#8B0000',
    },
    option: {
        width: 5,
        height: 15,
        alignSelf: 'flex-end',
        marginLeft:50,
        borderColor:'#8B0000',
    },
    rtPFP: {
        width: 150,
        height: 150,
        margin: 10,
        marginBottom: 10,
        borderWidth: 2,
        borderRadius: 550,
        borderColor:'#8B0000',
    },
});

export default MyStyles